---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami-labs
  namespace: flux-system
spec:
  interval: 4h0m0s
  url: https://bitnami-labs.github.io/sealed-secrets/

