---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: flux-telegram-notification
  namespace: flux-system
spec:
  type: generic
  address: http://flux-telegram-notification:8080/v1/event/7055881
