---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-prometheus
  namespace: rook-ceph

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-monitor
  namespace: monitoring
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rook-ceph-metrics
  namespace: rook-ceph
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBindingList
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: rook-ceph-metrics
    namespace: rook-ceph
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: rook-ceph-metrics
  subjects:
  - kind: ServiceAccount
    name: rook-prometheus
    namespace: rook-ceph
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: rook-ceph-monitor
    namespace: monitoring
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: rook-ceph-monitor
  subjects:
  - kind: ServiceAccount
    name: rook-prometheus
    namespace: rook-ceph
