apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    password: AgBf2XXgW9sSqJyFUk1sOtiSpniZXS5m27THi84NT9IzarBI8zDACVmrk/Xc0XrkcNFzvI/e1LPF70PbHRhzQ8DxFV1JPkseA/HLbttcnwzgtNTgxFWGxNSWoo0kg8Zmc/lzMCNuOBF2X+JeN7BUT0pFhP8G19bXDZWsfwH44M1oUR6EByRAszPiZRGEFeNPeQMtV/fcEOG4nvc5xSr5pZKdbz1LNVNh2s9gquef9xyIyhsxoVKGzQaodO10HYuWSRS99/Oz7Ryp3WSHp3tJdfyKt5BYZGPbITyNTM7GJ61bSPUDGN1F+W3yukgHLVA258scFMNT0mQbr8MQgzjMbOXKdBGbu31pBKS+BKnZo3tJp4B+7eKJvGxGmvLOAj2byTic0rR9jPRDpkWhNP+5DEAr6mI8fiSUZun9qMAebyxxCqRmZglrGlu5YPAlJzSW09QsYikVemdJu+rwrZrb6SU357MURQOf3hMJ4JNzcvV6SSvWZYLRryoloQ45HQQ13iJDIOrhjcOwon9nb1+p5gOkMRi5Fxm56xPmuFZ1o2QRV2jMVk3fta7ozWtNDEByjadzm/SBzopGfQLtkyKPa78s2eov3Fmhon0ywfZuwPvKNgpGhvZulbycHbQ/80j2685KnPvFVQ1RW48Tvp21oNF7GABZ+kT3XsbcFhl2H/oa4jl5l7xJA60uWjWFbDNEpk8pOCpVThypjRcvpQk=
    user: AgAf1GMCzDbsvuvXZKfYZ/WQqJ7SDmpma+j7u46j5pGwrtI3KDX16ruuw1mjqhoGtmqvCerHi0GnG9jPqI2gOjr3AvKMzSWVMHQQeMnN/1Vj9/pWc7+Y1qvmMpdKRvc5OMdOuisz74fln/kwVgXw8EizMdoPzGbfugBzv+4RO6P3qtGVv4U8aHOypLeRM8ckASxjcBLmY81btXGr5NrJrKdJJNykhyCMyMnqb44XDEyXpcCD3NlHvedbaasHpsNjkBPD4oQz++h/1HIY7BKgQlsrEEpgA5dHfLnrTqQnQFsjFrptNNhOIUvAU4wLJdNQ+qCa6k2ou5kJDRi0KqDeoMYNlB+gbXwSt5aUNEwvoCGWmhORhn3cDefdqPDD7Lb/M37KsuW2NFWha+RFampZ15rfezMrljz2y/6WvVSWR9t6uDFUkcMEGUm06iUSPOtiVMbrAp4LYcVBQ8xLYUP9io6Dj5rdW3VWaMswKrz9k0YsBrQd5k/wM1/jK+uS5DjNtFtbX2gn3/lO/HhQgqbIny5SiU9m5yyWj/0RyRspRp9y67ObEbXSt7diYKykf9WC2G6L9ZyyIKk+wcZ0Dh4EoQiSJuGpYsHQ2qpRu8DiQ+2hOjHefQozHPkyIJ4vMOFslR5NHY+KNxEPtXxfC0VasUN6YynSbN1LuBXz9t1hWjm4gePlhzO2tlw5AmClnkrnB0kHnYonNQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring

